SET MODE PostgreSQL;

SET REFERENTIAL_INTEGRITY FALSE;

DROP TABLE IF EXISTS activity;
DROP TABLE IF EXISTS attachment;
DROP TABLE IF EXISTS contact;
DROP TABLE IF EXISTS databasechangelog;
DROP TABLE IF EXISTS databasechangeloglock;
DROP TABLE IF EXISTS mail_case;
DROP TABLE IF EXISTS profile;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS reference;
DROP TABLE IF EXISTS sprint;
DROP TABLE IF EXISTS task;
DROP TABLE IF EXISTS task_tag;
DROP TABLE IF EXISTS user_belong;
DROP TABLE IF EXISTS user_role;
DROP TABLE IF EXISTS users;

DROP SEQUENCE IF EXISTS activity_id_seq;
DROP SEQUENCE IF EXISTS attachment_id_seq;
DROP SEQUENCE IF EXISTS mail_case_id_seq;
DROP SEQUENCE IF EXISTS project_id_seq;
DROP SEQUENCE IF EXISTS reference_id_seq;
DROP SEQUENCE IF EXISTS sprint_id_seq;
DROP SEQUENCE IF EXISTS task_id_seq;
DROP SEQUENCE IF EXISTS user_belong_id_seq;
DROP SEQUENCE IF EXISTS users_id_seq;

SET REFERENTIAL_INTEGRITY TRUE;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    endpoint     TIMESTAMP,
    startpoint   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    display_name VARCHAR(32) NOT NULL,
    email        VARCHAR(128) NOT NULL,
    first_name   VARCHAR(32) NOT NULL,
    last_name    VARCHAR(32),
    password     VARCHAR(255) NOT NULL
);
CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE profile (
    id BIGINT NOT NULL,
    last_failed_login TIMESTAMP,
    last_login        TIMESTAMP,
    mail_notifications BIGINT
);

CREATE TABLE contact (
    id   BIGINT NOT NULL,
    code VARCHAR(32) NOT NULL,
    value VARCHAR(256) NOT NULL
);

CREATE TABLE project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    endpoint   TIMESTAMP,
    startpoint TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title      VARCHAR(1024) NOT NULL,
    code       VARCHAR(32)   NOT NULL,
    description VARCHAR(4096) NOT NULL,
    parent_id  BIGINT,
    type_code  VARCHAR(32) NOT NULL DEFAULT 'DEFAULT'
);
CREATE SEQUENCE IF NOT EXISTS project_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE sprint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    endpoint   TIMESTAMP,
    startpoint TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    code       VARCHAR(32) NOT NULL,
    project_id BIGINT,
    status_code VARCHAR(32) NOT NULL
);
CREATE SEQUENCE IF NOT EXISTS sprint_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    endpoint   TIMESTAMP,
    startpoint TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title      VARCHAR(1024) NOT NULL,
    parent_id  BIGINT,
    project_id BIGINT,
    sprint_id  BIGINT,
    status_code VARCHAR(32) NOT NULL,
    type_code   VARCHAR(32) NOT NULL
);
CREATE SEQUENCE IF NOT EXISTS task_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    author_id BIGINT NOT NULL,
    task_id   BIGINT NOT NULL,
    updated   TIMESTAMP,
    comment   VARCHAR(4096),
    title     VARCHAR(1024) NOT NULL,
    description VARCHAR(4096),
    estimate  INTEGER,
    type_code VARCHAR(32) NOT NULL,
    status_code VARCHAR(32) NOT NULL,
    priority_code VARCHAR(32)
);
CREATE SEQUENCE IF NOT EXISTS activity_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR(128) NOT NULL,
    date_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    file_link VARCHAR(2048) NOT NULL,
    object_id BIGINT NOT NULL,
    object_type SMALLINT NOT NULL,
    user_id   BIGINT NOT NULL
);
CREATE SEQUENCE IF NOT EXISTS attachment_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE task_tag (
    task_id BIGINT NOT NULL,
    tag     VARCHAR(255)
);

CREATE TABLE user_belong (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    endpoint   TIMESTAMP,
    startpoint TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    object_id  BIGINT NOT NULL,
    object_type SMALLINT NOT NULL,
    user_id    BIGINT NOT NULL,
    user_type_code VARCHAR(32) NOT NULL
);
CREATE SEQUENCE IF NOT EXISTS user_belong_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE user_role (
    user_id BIGINT NOT NULL,
    role    SMALLINT
);

CREATE TABLE reference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    endpoint   TIMESTAMP,
    startpoint TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title      VARCHAR(1024) NOT NULL,
    aux        VARCHAR,
    code       VARCHAR(32) NOT NULL,
    ref_type   SMALLINT NOT NULL
);
CREATE SEQUENCE IF NOT EXISTS reference_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE mail_case (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email    VARCHAR(255) NOT NULL,
    name     VARCHAR(255) NOT NULL,
    date_time TIMESTAMP NOT NULL,
    result   VARCHAR(255) NOT NULL,
    template VARCHAR(255) NOT NULL
);
CREATE SEQUENCE IF NOT EXISTS mail_case_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE databasechangelog (
    id VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    filename VARCHAR(255) NOT NULL,
    dateexecuted TIMESTAMP NOT NULL,
    orderexecuted INTEGER NOT NULL,
    exectype VARCHAR(10) NOT NULL,
    md5sum VARCHAR(35),
    description VARCHAR(255),
    comments VARCHAR(255),
    tag VARCHAR(255),
    liquibase VARCHAR(20),
    conCLOBs VARCHAR(255),
    labels VARCHAR(255),
    deployment_id VARCHAR(10)
);
CREATE TABLE databasechangeloglock (
    id INTEGER NOT NULL,
    locked BOOLEAN NOT NULL,
    lockgranted TIMESTAMP,
    lockedby VARCHAR(255)
);

ALTER TABLE activity       ADD CONSTRAINT activity_pkey    PRIMARY KEY (id);
ALTER TABLE attachment     ADD CONSTRAINT attachment_pkey  PRIMARY KEY (id);
ALTER TABLE contact        ADD CONSTRAINT contact_pkey     PRIMARY KEY (id, code);
ALTER TABLE databasechangeloglock ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);
ALTER TABLE mail_case      ADD CONSTRAINT mail_case_pkey   PRIMARY KEY (id);
ALTER TABLE profile        ADD CONSTRAINT profile_pkey     PRIMARY KEY (id);
ALTER TABLE project        ADD CONSTRAINT project_pkey     PRIMARY KEY (id);
ALTER TABLE reference      ADD CONSTRAINT reference_pkey   PRIMARY KEY (id);
ALTER TABLE sprint         ADD CONSTRAINT sprint_pkey      PRIMARY KEY (id);
ALTER TABLE task           ADD CONSTRAINT task_pkey        PRIMARY KEY (id);
ALTER TABLE user_belong    ADD CONSTRAINT user_belong_pkey PRIMARY KEY (id);
ALTER TABLE users          ADD CONSTRAINT users_pkey       PRIMARY KEY (id);

ALTER TABLE project        ADD CONSTRAINT uk_project_code            UNIQUE (code);
ALTER TABLE reference      ADD CONSTRAINT uk_reference_ref_type_code UNIQUE (ref_type, code);
ALTER TABLE task_tag       ADD CONSTRAINT uk_task_tag                UNIQUE (task_id, tag);
ALTER TABLE user_belong    ADD CONSTRAINT uk_user_belong             UNIQUE (object_id, object_type, user_id, user_type_code);
ALTER TABLE user_role      ADD CONSTRAINT uk_user_role               UNIQUE (user_id, role);
ALTER TABLE users          ADD CONSTRAINT uk_users_display_name      UNIQUE (display_name);
ALTER TABLE users          ADD CONSTRAINT uk_users_email             UNIQUE (email);

ALTER TABLE profile
    ADD CONSTRAINT fk_profile_users    FOREIGN KEY (id)        REFERENCES users(id)   ON DELETE CASCADE;

ALTER TABLE contact
    ADD CONSTRAINT fk_contact_profile  FOREIGN KEY (id)        REFERENCES profile(id) ON DELETE CASCADE;

ALTER TABLE project
    ADD CONSTRAINT fk_project_parent   FOREIGN KEY (parent_id) REFERENCES project(id) ON DELETE CASCADE;

ALTER TABLE sprint
    ADD CONSTRAINT fk_sprint_project   FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE;

ALTER TABLE task
    ADD CONSTRAINT fk_task_parent_task FOREIGN KEY (parent_id)  REFERENCES task(id)    ON DELETE CASCADE;
ALTER TABLE task
    ADD CONSTRAINT fk_task_project     FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE;
ALTER TABLE task
    ADD CONSTRAINT fk_task_sprint      FOREIGN KEY (sprint_id)  REFERENCES sprint(id)  ON DELETE SET NULL;

ALTER TABLE activity
    ADD CONSTRAINT fk_activity_users   FOREIGN KEY (author_id)  REFERENCES users(id)   ON DELETE CASCADE;
ALTER TABLE activity
    ADD CONSTRAINT fk_activity_task    FOREIGN KEY (task_id)    REFERENCES task(id)    ON DELETE CASCADE;

ALTER TABLE attachment
    ADD CONSTRAINT fk_attachment       FOREIGN KEY (user_id)    REFERENCES users(id)   ON DELETE CASCADE;

ALTER TABLE task_tag
    ADD CONSTRAINT fk_task_tag         FOREIGN KEY (task_id)    REFERENCES task(id)    ON DELETE CASCADE;

ALTER TABLE user_belong
    ADD CONSTRAINT fk_user_belong      FOREIGN KEY (user_id)    REFERENCES users(id)   ON DELETE CASCADE;
