-- PostgreSQL production schema (Liquibase raw SQL)
-- ВАЖЛИВО: без CREATE SEQUENCE і без databasechangelog* таблиць

-- =========================
-- Таблиці
-- =========================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    endpoint TIMESTAMP,
    startpoint TIMESTAMP NOT NULL,
    display_name VARCHAR(32) NOT NULL,
    email VARCHAR(128) NOT NULL,
    first_name VARCHAR(32) NOT NULL,
    last_name VARCHAR(32),
    password VARCHAR(255),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk_users_display_name UNIQUE (display_name),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE profile (
    id BIGINT NOT NULL,
    last_failed_login TIMESTAMP,
    last_login TIMESTAMP,
    mail_notifications BIGINT,
    CONSTRAINT profile_pkey PRIMARY KEY (id),
    CONSTRAINT fk_profile_users FOREIGN KEY (id) REFERENCES users(id)
);

CREATE TABLE contact (
    code VARCHAR(255) NOT NULL,
    id BIGINT NOT NULL,
    value VARCHAR(256) NOT NULL,
    CONSTRAINT contact_pkey PRIMARY KEY (code, id),
    CONSTRAINT fk_contact_profile FOREIGN KEY (id) REFERENCES profile(id)
);

CREATE TABLE project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    endpoint TIMESTAMP,
    startpoint TIMESTAMP NOT NULL,
    title VARCHAR(1024) NOT NULL,
    code VARCHAR(32) NOT NULL,
    description VARCHAR(4096) NOT NULL,
    parent_id BIGINT,
    type_code VARCHAR(32) NOT NULL,
    CONSTRAINT project_pkey PRIMARY KEY (id),
    CONSTRAINT uk_project_code UNIQUE (code),
    CONSTRAINT fk_project_parent FOREIGN KEY (parent_id) REFERENCES project(id) ON DELETE CASCADE
);

CREATE TABLE sprint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    endpoint TIMESTAMP,
    startpoint TIMESTAMP NOT NULL,
    code VARCHAR(32) NOT NULL,
    project_id BIGINT,
    status_code VARCHAR(32) NOT NULL,
    CONSTRAINT sprint_pkey PRIMARY KEY (id),
    CONSTRAINT fk_sprint_project FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    endpoint TIMESTAMP,
    startpoint TIMESTAMP NOT NULL,
    title VARCHAR(1024) NOT NULL,
    parent_id BIGINT,
    project_id BIGINT,
    sprint_id BIGINT,
    status_code VARCHAR(32) NOT NULL,
    type_code VARCHAR(32) NOT NULL,
    CONSTRAINT task_pkey PRIMARY KEY (id),
    CONSTRAINT fk_task_parent_task FOREIGN KEY (parent_id) REFERENCES task(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_project FOREIGN KEY (project_id) REFERENCES project(id),
    CONSTRAINT fk_task_sprint FOREIGN KEY (sprint_id) REFERENCES sprint(id)
);

CREATE TABLE activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    author_id BIGINT NOT NULL,
    task_id BIGINT NOT NULL,
    updated TIMESTAMP,
    comment VARCHAR(4096),
    title VARCHAR(1024) NOT NULL,
    description VARCHAR(4096),
    estimate INTEGER,
    type_code VARCHAR(32) NOT NULL,
    status_code VARCHAR(32) NOT NULL,
    priority_code VARCHAR(32),
    CONSTRAINT activity_pkey PRIMARY KEY (id),
    CONSTRAINT fk_activity_users FOREIGN KEY (author_id) REFERENCES users(id),
    CONSTRAINT fk_activity_task FOREIGN KEY (task_id) REFERENCES task(id)
);

CREATE TABLE attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(128) NOT NULL,
    date_time TIMESTAMP DEFAULT NOW(),
    file_link VARCHAR(255) NOT NULL,
    object_id BIGINT NOT NULL,
    object_type SMALLINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT attachment_pkey PRIMARY KEY (id),
    CONSTRAINT fk_attachment FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE task_tag (
    task_id BIGINT NOT NULL,
    tag VARCHAR(255),
    CONSTRAINT uk_task_tag UNIQUE (task_id, tag),
    CONSTRAINT fk_task_tag FOREIGN KEY (task_id) REFERENCES task(id) ON DELETE CASCADE
);

CREATE TABLE user_belong (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    endpoint TIMESTAMP,
    startpoint TIMESTAMP NOT NULL,
    object_id BIGINT NOT NULL,
    object_type SMALLINT NOT NULL,
    user_id BIGINT NOT NULL,
    user_type_code VARCHAR(32) NOT NULL,
    CONSTRAINT user_belong_pkey PRIMARY KEY (id),
    CONSTRAINT uk_user_belong UNIQUE (object_id, object_type, user_id, user_type_code),
    CONSTRAINT fk_user_belong FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_role (
    user_id BIGINT NOT NULL,
    role SMALLINT,
    CONSTRAINT uk_user_role UNIQUE (user_id, role),
    CONSTRAINT fk_user_role FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE reference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    endpoint TIMESTAMP,
    startpoint TIMESTAMP NOT NULL,
    title VARCHAR(1024) NOT NULL,
    aux VARCHAR,
    code VARCHAR(32) NOT NULL,
    ref_type SMALLINT NOT NULL,
    CONSTRAINT reference_pkey PRIMARY KEY (id),
    CONSTRAINT uk_reference_ref_type_code UNIQUE (ref_type, code)
);

CREATE TABLE mail_case (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    date_time TIMESTAMP NOT NULL,
    result VARCHAR(255) NOT NULL,
    template VARCHAR(255) NOT NULL,
    CONSTRAINT mail_case_pkey PRIMARY KEY (id)
);
