CREATE TABLE activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    author_id BIGINT NOT NULL,
    task_id BIGINT NOT NULL,
    updated TIMESTAMP,
    comment VARCHAR(4096),
    title VARCHAR(1024) NOT NULL,
    description VARCHAR(4096),
    estimate INTEGER,
    type_code VARCHAR(32) NOT NULL,
    status_code VARCHAR(32) NOT NULL,
    priority_code VARCHAR(32)
);

CREATE SEQUENCE activity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(128) NOT NULL,
    date_time TIMESTAMP DEFAULT NOW(),
    file_link VARCHAR(255) NOT NULL,
    object_id BIGINT NOT NULL,
    object_type SMALLINT NOT NULL,
    user_id BIGINT NOT NULL
);

CREATE SEQUENCE attachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE contact (
    code VARCHAR(255) NOT NULL,
    id BIGINT NOT NULL,
    value VARCHAR(256) NOT NULL
);

CREATE TABLE databasechangelog (
    id VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    filename VARCHAR(255) NOT NULL,
    dateexecuted TIMESTAMP NOT NULL,
    orderexecuted INTEGER NOT NULL,
    exectype VARCHAR(10) NOT NULL,
    md5sum VARCHAR(35),
    description VARCHAR(255),
    comments VARCHAR(255),
    tag VARCHAR(255),
    liquibase VARCHAR(20),
    conCLOBs VARCHAR(255),
    labels VARCHAR(255),
    deployment_id VARCHAR(10)
);

CREATE TABLE databasechangeloglock (
    id INTEGER NOT NULL,
    locked BOOLEAN NOT NULL,
    lockgranted TIMESTAMP,
    lockedby VARCHAR(255)
);

CREATE TABLE mail_case (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    date_time TIMESTAMP NOT NULL,
    result VARCHAR(255) NOT NULL,
    template VARCHAR(255) NOT NULL
);

CREATE SEQUENCE mail_case_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE profile (
    id BIGINT NOT NULL,
    last_failed_login TIMESTAMP,
    last_login TIMESTAMP,
    mail_notifications BIGINT
);

CREATE TABLE project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    endpoint TIMESTAMP,
    startpoint TIMESTAMP NOT NULL,
    title VARCHAR(1024) NOT NULL,
    code VARCHAR(32) NOT NULL,
    description VARCHAR(4096) NOT NULL,
    parent_id BIGINT,
    type_code VARCHAR(32) NOT NULL
);

CREATE SEQUENCE project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE reference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    endpoint TIMESTAMP,
    startpoint TIMESTAMP NOT NULL,
    title VARCHAR(1024) NOT NULL,
    aux VARCHAR,
    code VARCHAR(32) NOT NULL,
    ref_type SMALLINT NOT NULL
);

CREATE SEQUENCE reference_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE sprint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    endpoint TIMESTAMP,
    startpoint TIMESTAMP NOT NULL,
    code VARCHAR(32) NOT NULL,
    project_id BIGINT,
    status_code VARCHAR(32) NOT NULL
);

CREATE SEQUENCE sprint_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    endpoint TIMESTAMP,
    startpoint TIMESTAMP NOT NULL,
    title VARCHAR(1024) NOT NULL,
    parent_id BIGINT,
    project_id BIGINT,
    sprint_id BIGINT,
    status_code VARCHAR(32) NOT NULL,
    type_code VARCHAR(32) NOT NULL
);

CREATE SEQUENCE task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE task_tag (
    task_id BIGINT NOT NULL,
    tag VARCHAR(255)
);

CREATE TABLE user_belong (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    endpoint TIMESTAMP,
    startpoint TIMESTAMP NOT NULL,
    object_id BIGINT NOT NULL,
    object_type SMALLINT NOT NULL,
    user_id BIGINT NOT NULL,
    user_type_code VARCHAR(32) NOT NULL
);

CREATE SEQUENCE user_belong_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE user_role (
    user_id BIGINT NOT NULL,
    role SMALLINT
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    endpoint TIMESTAMP,
    startpoint TIMESTAMP NOT NULL,
    display_name VARCHAR(32) NOT NULL,
    email VARCHAR(128) NOT NULL,
    first_name VARCHAR(32) NOT NULL,
    last_name VARCHAR(32),
    password VARCHAR(255)
);

CREATE SEQUENCE users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- =========================
-- Primary keys
-- =========================
ALTER TABLE activity  ADD CONSTRAINT activity_pkey  PRIMARY KEY (id);
ALTER TABLE attachment ADD CONSTRAINT attachment_pkey PRIMARY KEY (id);
ALTER TABLE contact    ADD CONSTRAINT contact_pkey    PRIMARY KEY (code, id);
ALTER TABLE databasechangeloglock ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);
ALTER TABLE mail_case  ADD CONSTRAINT mail_case_pkey  PRIMARY KEY (id);
ALTER TABLE profile    ADD CONSTRAINT profile_pkey    PRIMARY KEY (id);
ALTER TABLE project    ADD CONSTRAINT project_pkey    PRIMARY KEY (id);
ALTER TABLE reference  ADD CONSTRAINT reference_pkey  PRIMARY KEY (id);
ALTER TABLE sprint     ADD CONSTRAINT sprint_pkey     PRIMARY KEY (id);
ALTER TABLE task       ADD CONSTRAINT task_pkey       PRIMARY KEY (id);
ALTER TABLE user_belong ADD CONSTRAINT user_belong_pkey PRIMARY KEY (id);
ALTER TABLE users      ADD CONSTRAINT users_pkey      PRIMARY KEY (id);

-- =========================
-- Unique constraints
-- =========================
ALTER TABLE project   ADD CONSTRAINT uk_project_code UNIQUE (code);
ALTER TABLE reference ADD CONSTRAINT uk_reference_ref_type_code UNIQUE (ref_type, code);
ALTER TABLE task_tag  ADD CONSTRAINT uk_task_tag UNIQUE (task_id, tag);
ALTER TABLE user_belong ADD CONSTRAINT uk_user_belong UNIQUE (object_id, object_type, user_id, user_type_code);
ALTER TABLE user_role ADD CONSTRAINT uk_user_role UNIQUE (user_id, role);
ALTER TABLE users     ADD CONSTRAINT uk_users_display_name UNIQUE (display_name);
ALTER TABLE users     ADD CONSTRAINT uk_users_email UNIQUE (email);

-- =========================
-- Foreign keys
-- =========================
ALTER TABLE activity   ADD CONSTRAINT fk_activity_users  FOREIGN KEY (author_id) REFERENCES users(id);
ALTER TABLE activity   ADD CONSTRAINT fk_activity_task   FOREIGN KEY (task_id)   REFERENCES task(id);

ALTER TABLE attachment ADD CONSTRAINT fk_attachment      FOREIGN KEY (user_id)   REFERENCES users(id);

ALTER TABLE contact    ADD CONSTRAINT fk_contact_profile FOREIGN KEY (id)        REFERENCES profile(id);

ALTER TABLE profile    ADD CONSTRAINT fk_profile_users   FOREIGN KEY (id)        REFERENCES users(id);

ALTER TABLE project    ADD CONSTRAINT fk_project_parent  FOREIGN KEY (parent_id) REFERENCES project(id) ON DELETE CASCADE;

ALTER TABLE sprint     ADD CONSTRAINT fk_sprint_project  FOREIGN KEY (project_id) REFERENCES project(id);

ALTER TABLE task       ADD CONSTRAINT fk_task_parent_task FOREIGN KEY (parent_id) REFERENCES task(id) ON DELETE CASCADE;
ALTER TABLE task       ADD CONSTRAINT fk_task_project     FOREIGN KEY (project_id) REFERENCES project(id);
ALTER TABLE task       ADD CONSTRAINT fk_task_sprint      FOREIGN KEY (sprint_id)  REFERENCES sprint(id);

ALTER TABLE task_tag   ADD CONSTRAINT fk_task_tag         FOREIGN KEY (task_id)    REFERENCES task(id) ON DELETE CASCADE;

ALTER TABLE user_belong ADD CONSTRAINT fk_user_belong     FOREIGN KEY (user_id)    REFERENCES users(id);

ALTER TABLE user_role  ADD CONSTRAINT fk_user_role        FOREIGN KEY (user_id)    REFERENCES users(id) ON DELETE CASCADE;
