app:
  host-url: ${APP_HOST_URL:http://localhost:8080}
  test-mail: ${APP_TEST_MAIL:jira4jr@gmail.com}
  templates-update-cache: 5s
  mail-sending-props:
    core-pool-size: 8
    max-pool-size: 100

spring:
  init:
    mode: never

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
        jdbc:
          time_zone: UTC

  liquibase:
    change-log: classpath:db/changelog.sql

  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none

  cache:
    cache-names: users
    caffeine:
      spec: maximumSize=10000,expireAfterAccess=5m

  sql:
    init:
      mode: never

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    check-template-location: false

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
          github:
            client-id: ${GITHUB_CLIENT_ID:}
            client-secret: ${GITHUB_CLIENT_SECRET:}
          gitlab:
            client-id: ${GITLAB_CLIENT_ID:}
            client-secret: ${GITLAB_CLIENT_SECRET:}
        provider: {}

logging:
  level:
    root: WARN
    com.javarush.jira: DEBUG
    com.javarush.jira.common.config.MvcConfig: WARN
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

server:
  forward-headers-strategy: framework
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
  swagger-ui:
    path: /doc
