app:
  host-url: ${APP_HOST_URL:http://localhost:8080}
  test-mail: ${APP_TEST_MAIL:jira4jr@gmail.com}

server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
  main:
    web-application-type: servlet

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog.sql
  sql:
    init:
      mode: never

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

spring.security.oauth2.client:
  registration: {}
  provider: {}
